@baseUrl = http://localhost:3000/api/v1/
@jwt_token = jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YTUzMGNmYWUzYWRlZWQ3YTk5NTA3YiIsImlhdCI6MTcyMjY3NjA4OSwiZXhwIjoxNzIyNzYyNDg5fQ.xNPVuIF-ANRNgbth8CEj4zt9GwiPcPDgvl3IXH-mS-4;

#CREATE USER
POST http://localhost:3000/api/v1/users/register  HTTP/1.1 
content-type: application/json

{
  "firstName": "test  ",
  "lastName": "<div>Ademola</div>",
  "email": "luk@example.com",
  "password": "test1234",
  "passwordConfirm": "test1234",
  "position": "Principal",
  "phone":"12344555",
  "gender":"male",
  "address":"address",
  "yearOfCall": "2010-01-01",
  "practiceArea": "Property Law",
  "universityAttended": "University of UI",
  "lawSchoolAttended": "Lagos, Law School"
}

###

POST  {{baseUrl}}users/login  HTTP/1.1 
content-type: application/json

{
  "email":"admin2@gmail.com",
  "password":"test1234"
}

###
POST  {{baseUrl}}users/sendWithCode/admin2@gmail.com  HTTP/1.1 
content-type: application/json

{
  "loginCode":"555768"
}

  # "email":{"$gt":""},

### login with google

POST  http://localhost:3000/api/v1/users//google/callback  HTTP/1.1 
content-type: application/json

{
  "userToken":"1212121"
}

### access code

POST  http://localhost:3000/api/v1/users/sendLoginCode/asinmi4real@gmail.com  HTTP/1.1 
content-type: application/json

### login user with access code
POST  http://localhost:3000/api/v1/users/loginWithcode/asinmi4real@gmail.com  HTTP/1.1 
content-type: application/json

{
  "loginCode":"555768"
}


###

GET http://localhost:3000/api/v1/users/www  HTTP/1.1 
content-type: application/json

###

#CREATE TASKS
POST http://localhost:3000/api/v1/clients/forgotpassword HTTP/1.1 
content-type: application/json

{
 "email": "fedmin@gmail.com"
}


###

# GET TASKS
GET http://localhost:3000/api/v1/tasks  HTTP/1.1 
content-type: application/json

###

# GET CASES
GET http://localhost:3000/api/v1/cases  HTTP/1.1 
Authorization: Bearer {{jwt_token}}

###
# forgot password
POST http://localhost:3000/api/v1/clients/forgotpassword  HTTP/1.1 
content-type: application/json
{
  "email": "fedmin@gmail.com"
}


###
POST http://localhost:3000/api/v1/cases  HTTP/1.1 
content-type: application/json

{
  "firstParty": {
    "title": "Applicant",
    "processesFiled": [{"name":"Complaint", "name": "Interrogatories"}],
    "description": [{"name":"Adeleke"}]
  },
  "secondParty": {
    "title": "Respondent",
    "processesFiled": [{"name":"Answer to Complaint"},  {"name":"Motion to Dismiss"}],
    "description": [{"name":"Aduku"}]
  },
  "otherParty": [{
    "title": "Third Party",
    "processesFiled": [{"name":"Answer to Complaint"},  {"name":"Motion to Dismiss"}],
    "description": [{"name":"Aduku"}]
  },
  
  {
    "title": "Respondent",
    "processesFiled": [{"name":"Answer to Complaint"},  {"name":"Motion to Dismiss"}],
    "description": [{"name":"Aduku"}]
  }
  ],
  "suitNo": "SC/723/2023",
  "caseOfficeFileNo": "FA/89/2023",
  "courtName": "Court of Appeal",
  "judge": {
    "name": ["Justice Sarah Clark"]
  },
  "caseSummary": "The case involves a dispute over contract terms between the plaintiff and the defendant. Both parties have presented evidence supporting their claims.",
  "caseStatus": "Pending",
  "natureOfCase": "Contract Dispute",
  "filingDate": "2023-05-10T00:00:00.000Z",
  "modeOfCommencement": "Originating Summons",
  "otherModeOfCommencement": "",
  "caseStrengths": ["Clear contract terms"],
  "caseWeaknesses": ["Ambiguity in clauses"],
  "casePriority": "Medium",
  "stepToBeTaken": ["Schedule mediation session"],
  "caseUpdates": [
    {
      "date": "2023-05-12T00:00:00.000Z",
      "update": "Complaint filed"
    },
    {
      "date": "2023-05-15T00:00:00.000Z",
      "update": "Defendant responded to complaint"
    }
  ],
  "task": [],
  "accountOfficer": [],
  "client": ["ABC Corporation", "XYZ Inc."],
  "generalComment": "Parties are willing to explore settlement options."
}



###

# GET Invoices
GET {{baseUrl}}invoices  HTTP/1.1 
content-type: application/json

###
#UPDATE CASE
PUT http://localhost:3000/api/v1/cases/65eb95d4c01ab9677c341bfbc  HTTP/1.1 

{
  "caseStatus":"Closed"
}


###

DELETE http://localhost:3000/api/v1/cases/65f2115493203c719c17392e  HTTP/1.1 
content-type: application/json

###
 #GET USERS
GET http://localhost:3000/api/v1/users  HTTP/1.1 
content-type: application/json

###

#CREATE CLIENT
POST http://localhost:3000/api/v1/clients  HTTP/1.1 
content-type: application/json

{
  "firstName": "John",
  "secondName": "Doe",
  "middleName": "Michael",
  "email": "john.doe@example.com",
  "case": "61630f9d070f9c27a8350c21" 
}


###

# GET CLIENTS
GET http://localhost:3000/api/v1/clients  HTTP/1.1 
content-type: application/json

###
GET http://localhost:3000/api/v1/uploads/6639edcf4b99c7ad3af85dca  HTTP/1.1 
content-type: application/json

###
GET http://localhost:3000/api/v1/uploads/photos/6639edcf4b99c7ad3af85dca  HTTP/1.1 
content-type: application/json

###
GET {{baseUrl}}cases/case-status  HTTP/1.1 
content-type: application/json

###
GET {{baseUrl}}reports/pdf/causeList/week  HTTP/1.1 
content-type: application/json
###
GET {{baseUrl}}payments/paymentEachClient HTTP/1.1 
content-type: application/json
###
GET {{baseUrl}}payments/client/665df5b07108ca4adc18a65c/case/6683152cddcd8e8eae3309c7 HTTP/1.1 
content-type: application/json


# reports
###
GET {{baseUrl}}reports HTTP/1.1 
content-type: application/json


###
POST  {{baseUrl}}leaves/applications HTTP/1.1 
content-type: application/json


{
  "startDate":"2024-08-11",
  "endDate":"2024-08-21",
  "applyTo": "admin2@gmail.com"
}