const CAMA_2020 = require("./camaConstants");

const COMPLIANCE_TYPES = {
  ANNUAL_RETURN: {
    code: "ANNUAL_RETURN",
    name: "Annual Returns",
    description: "Annual filing showing company status, directors, shareholders, and share capital",
    category: "ANNUAL_RETURNS",
    filingDeadline: {
      "business-name": null,
      "private-limited": null,
      "public-limited": null,
      llp: null,
      "incorporated-trustee": null,
    },
    gracePeriodDays: 0,
    penaltyType: "daily",
    autoGenerated: true,
  },
  AGM: {
    code: "AGM",
    name: "Annual General Meeting",
    description: "Required meeting to present financial statements and appoint directors",
    category: "ANNUAL_RETURNS",
    applicableTo: ["private-limited", "public-limited", "llp"],
    exemptionApplicableTo: ["business-name"],
    firstMeetingMonths: 18,
    subsequentMonths: 15,
    gracePeriodDays: 0,
    penaltyType: "none",
    autoGenerated: true,
  },
  SCHEDULE_14_STATEMENT: {
    code: "SCHEDULE_14",
    name: "Schedule 14 Statement",
    description: "Financial statement filing with annual returns",
    category: "ANNUAL_RETURNS",
    filingDeadlineDays: 42,
    gracePeriodDays: 0,
    penaltyType: "daily",
    penaltyRate: { perDay: 100 },
    autoGenerated: true,
  },
  PSC_FILING: {
    code: "PSC",
    name: "People with Significant Control (PSC) Filing",
    description: "Filing beneficial ownership information for persons with 5%+ control",
    category: "PSC_COMPLIANCE",
    filingDeadlineDays: 30,
    gracePeriodDays: 0,
    penaltyType: "daily",
    penaltyRate: { min: 5000, max: 50000 },
    autoGenerated: true,
  },
  PSC_UPDATE: {
    code: "PSC_UPDATE",
    name: "PSC Update",
    description: "Update PSC information when ownership changes",
    category: "PSC_COMPLIANCE",
    filingDeadlineDays: 30,
    gracePeriodDays: 0,
    penaltyType: "daily",
    penaltyRate: { min: 5000, max: 50000 },
    autoGenerated: false,
  },
  DIRECTOR_CHANGE: {
    code: "DIRECTOR_CHANGE",
    name: "Change in Director Particulars",
    description: "Filing director appointments, resignations, or changes",
    category: "POST_INCORPORATION",
    filingDeadlineDays: 14,
    gracePeriodDays: 0,
    penaltyType: "fixed",
    penaltyRate: { amount: 5000 },
    autoGenerated: false,
  },
  SHAREHOLDING_CHANGE: {
    code: "SHAREHOLDING_CHANGE",
    name: "Change in Shareholding",
    description: "Filing share transfers or new share issuances",
    category: "POST_INCORPORATION",
    filingDeadlineDays: 14,
    gracePeriodDays: 0,
    penaltyType: "fixed",
    penaltyRate: { amount: 5000 },
    autoGenerated: false,
  },
  RETURN_OF_ALLOTMENT: {
    code: "ALLOTMENT",
    name: "Return of Allotment",
    description: "Filing when new shares are issued",
    category: "POST_INCORPORATION",
    filingDeadlineDays: 14,
    gracePeriodDays: 0,
    penaltyType: "fixed",
    penaltyRate: { "private-limited": 5000, "public-limited": 10000 },
    autoGenerated: false,
  },
  ADDRESS_CHANGE: {
    code: "ADDRESS_CHANGE",
    name: "Change in Registered Address",
    description: "Filing change of company's registered office",
    category: "POST_INCORPORATION",
    filingDeadlineDays: 14,
    gracePeriodDays: 0,
    penaltyType: "daily",
    penaltyRate: { perDay: 50 },
    autoGenerated: false,
  },
  SHARE_CAPITAL_INCREASE: {
    code: "SHARE_CAPITAL",
    name: "Increase in Share Capital",
    description: "Filing when company issues more shares",
    category: "POST_INCORPORATION",
    filingDeadlineDays: 14,
    gracePeriodDays: 0,
    penaltyType: "fixed",
    penaltyRate: { "private-limited": 5000, "public-limited": 10000 },
    autoGenerated: false,
  },
  NAME_CHANGE: {
    code: "NAME_CHANGE",
    name: "Change of Company Name",
    description: "Filing after special resolution and CAC approval",
    category: "POST_INCORPORATION",
    filingDeadlineDays: 14,
    gracePeriodDays: 0,
    penaltyType: "fixed",
    penaltyRate: { amount: 5000 },
    autoGenerated: false,
  },
  MEMORANDUM_ALTERATION: {
    code: "MEMO_ALTERATION",
    name: "Alteration of Memorandum & Articles",
    description: "Filing changes to company's constitution",
    category: "POST_INCORPORATION",
    filingDeadlineDays: 14,
    gracePeriodDays: 0,
    penaltyType: "fixed",
    penaltyRate: { amount: 5000 },
    autoGenerated: false,
  },
  CHARGE_REGISTRATION: {
    code: "CHARGE",
    name: "Company Charge Registration",
    description: "Registering charges/collateral on company assets",
    category: "CHARGES",
    filingDeadlineDays: 90,
    gracePeriodDays: 0,
    penaltyType: "fixed",
    penaltyRate: { "private-limited": 5000, "public-limited": 10000 },
    consequence: "Charge becomes void if not registered",
    autoGenerated: false,
  },
  CHARGE_RELEASE: {
    code: "CHARGE_RELEASE",
    name: "Notice of Deed of Release",
    description: "Filing when a charge is paid off and released",
    category: "CHARGES",
    filingDeadlineDays: 14,
    gracePeriodDays: 0,
    penaltyType: "fixed",
    penaltyRate: { amount: 5000 },
    autoGenerated: false,
  },
  LIQUIDATOR_APPOINTMENT: {
    code: "LIQUIDATOR",
    name: "Notice of Appointment of Liquidator",
    description: "Notifying CAC of liquidator appointment during winding up",
    category: "LIQUIDATION",
    filingDeadlineDays: 14,
    gracePeriodDays: 0,
    penaltyType: "fixed",
    penaltyRate: { amount: 5000 },
    autoGenerated: false,
  },
  WINDING_UP_RESOLUTION: {
    code: "WINDING_UP",
    name: "Resolution for Winding Up",
    description: "Filing shareholder resolution to wind up company",
    category: "LIQUIDATION",
    filingDeadlineDays: 14,
    gracePeriodDays: 0,
    penaltyType: "fixed",
    penaltyRate: { perPerson: 500 },
    autoGenerated: false,
  },
  BUSINESS_NAME_RENEWAL: {
    code: "BN_RENEWAL",
    name: "Business Name Renewal",
    description: "Renewal of business name registration (every 3 years)",
    category: "BUSINESS_NAME",
    filingDeadlineDays: 0,
    gracePeriodDays: 30,
    penaltyType: "fixed",
    renewalPeriodDays: 1095,
    penaltyRate: { registration: 20000 },
    autoGenerated: true,
  },
  STATEMENT_OF_AFFAIRS: {
    code: "DORMANT_FILING",
    name: "Statement of Affairs (Dormant Companies)",
    description: "Filing for registered but non-operational companies",
    category: "STATUTORY",
    filingDeadlineDays: 0,
    gracePeriodDays: 0,
    penaltyType: "strike_off",
    strikeOffYears: 10,
    autoGenerated: false,
  },
  CAC_QUERY_RESPONSE: {
    code: "CAC_QUERY",
    name: "CAC Query Response",
    description: "Response to CAC requests for information or clarification",
    category: "STATUTORY",
    filingDeadlineDays: 30,
    gracePeriodDays: 0,
    penaltyType: "administrative",
    autoGenerated: false,
  },
  MISC_FILING: {
    code: "MISC_FILING",
    name: "Other Document Filing",
    description: "Catch-all for other required CAC filings",
    category: "STATUTORY",
    filingDeadlineDays: 14,
    gracePeriodDays: 0,
    penaltyType: "fixed",
    penaltyRate: { amount: 5000 },
    autoGenerated: false,
  },
};

const PENALTY_RATES = {
  ANNUAL_RETURN: {
    annual: {
      "small-company": 3000,
      "private-limited": 5000,
      "public-limited": 10000,
      llp: 5000,
      "incorporated-trustee": 5000,
      "business-name": 3000,
      other: 5000,
    },
    daily: {
      "small-company": 250,
      "private-limited": 500,
      "public-limited": 1000,
      llp: 500,
      "incorporated-trustee": 250,
      "business-name": 250,
      other: 500,
    },
  },
  PSC: {
    daily: { min: 5000, max: 50000 },
  },
  AGM: {
    penalty: "prescribed_by_commission",
  },
  SCHEDULE_14: {
    daily: { perDay: 100 },
  },
  DIRECTOR_CHANGE: {
    fixed: { amount: 5000 },
  },
  SHAREHOLDING_CHANGE: {
    fixed: { amount: 5000 },
  },
  RETURN_OF_ALLOTMENT: {
    fixed: { "private-limited": 5000, "public-limited": 10000 },
  },
  ADDRESS_CHANGE: {
    daily: { perDay: 50 },
  },
  SHARE_CAPITAL_INCREASE: {
    fixed: { "private-limited": 5000, "public-limited": 10000 },
  },
  NAME_CHANGE: {
    fixed: { amount: 5000 },
  },
  MEMORANDUM_ALTERATION: {
    fixed: { amount: 5000 },
  },
  CHARGE_REGISTRATION: {
    fixed: { "private-limited": 5000, "public-limited": 10000 },
    consequence: "charge_void",
  },
  CHARGE_RELEASE: {
    fixed: { amount: 5000 },
  },
  LIQUIDATOR_APPOINTMENT: {
    fixed: { amount: 5000 },
  },
  WINDING_UP_RESOLUTION: {
    perPerson: { amount: 500 },
  },
  FALSE_INFORMATION: {
    criminal: {
      fine: 100000,
      imprisonment: { years: 2 },
      section: "462 CAMA 2020",
    },
  },
  BUSINESS_NAME_RENEWAL: {
    registration: 20000,
    latePenalty: 50000,
  },
  MISC_FILING: {
    fixed: { amount: 5000 },
  },
};

const COMPLIANCE_CATEGORIES = {
  ANNUAL_RETURNS: {
    name: "Annual Returns & Financial Reporting",
    icon: "file-text",
    color: "#3b82f6",
    complianceTypes: ["ANNUAL_RETURN", "AGM", "SCHEDULE_14_STATEMENT"],
  },
  PSC_COMPLIANCE: {
    name: "PSC (Beneficial Ownership)",
    icon: "users",
    color: "#8b5cf6",
    complianceTypes: ["PSC_FILING", "PSC_UPDATE"],
  },
  POST_INCORPORATION: {
    name: "Post-Incorporation Changes",
    icon: "edit",
    color: "#10b981",
    complianceTypes: [
      "DIRECTOR_CHANGE",
      "SHAREHOLDING_CHANGE",
      "RETURN_OF_ALLOTMENT",
      "ADDRESS_CHANGE",
      "SHARE_CAPITAL_INCREASE",
      "NAME_CHANGE",
      "MEMORANDUM_ALTERATION",
    ],
  },
  CHARGES: {
    name: "Charges & Security Interests",
    icon: "lock",
    color: "#f59e0b",
    complianceTypes: ["CHARGE_REGISTRATION", "CHARGE_RELEASE"],
  },
  LIQUIDATION: {
    name: "Liquidation & Winding Up",
    icon: "stop",
    color: "#ef4444",
    complianceTypes: ["LIQUIDATOR_APPOINTMENT", "WINDING_UP_RESOLUTION"],
  },
  BUSINESS_NAME: {
    name: "Business Name",
    icon: "shop",
    color: "#ec4899",
    complianceTypes: ["BUSINESS_NAME_RENEWAL"],
  },
  STATUTORY: {
    name: "Statutory Obligations",
    icon: "book",
    color: "#6b7280",
    complianceTypes: ["STATEMENT_OF_AFFAIRS", "CAC_QUERY_RESPONSE", "MISC_FILING"],
  },
};

const PORTAL_STATUS = {
  ACTIVE: { label: "Active", color: "#10b981", isGood: true },
  REGISTERED: { label: "Registered", color: "#10b981", isGood: true },
  COMPLIANT: { label: "Compliant", color: "#10b981", isGood: true },
  INACTIVE: { label: "Inactive", color: "#ef4444", isGood: false },
  STRUCK_OFF: { label: "Struck Off", color: "#dc2626", isGood: false },
  WOUND_UP: { label: "Wound Up", color: "#dc2626", isGood: false },
  DISSOLVED: { label: "Dissolved", color: "#dc2626", isGood: false },
  SUSPENDED: { label: "Suspended", color: "#f59e0b", isGood: false },
  UNKNOWN: { label: "Unknown", color: "#6b7280", isGood: null },
};

const BAD_PORTAL_STATUSES = ["INACTIVE", "STRUCK_OFF", "WOUND_UP", "DISSOLVED", "SUSPENDED"];
const GOOD_PORTAL_STATUSES = ["ACTIVE", "REGISTERED", "COMPLIANT"];

function getComplianceType(code) {
  return COMPLIANCE_TYPES[code] || null;
}

function getComplianceCategory(code) {
  for (const category of Object.values(COMPLIANCE_CATEGORIES)) {
    if (category.complianceTypes.includes(code)) {
      return category;
    }
  }
  return null;
}

function calculatePenalty(entityType, complianceTypeCode, daysLate = 0, officers = 1) {
  const complianceType = COMPLIANCE_TYPES[complianceTypeCode];
  if (!complianceType) return { total: 0, breakdown: [] };

  const penaltyConfig = PENALTY_RATES[complianceTypeCode];
  if (!penaltyConfig) return { total: 0, breakdown: [] };

  const breakdown = [];
  let total = 0;

  const effectiveDaysLate = Math.max(0, daysLate - (complianceType.gracePeriodDays || 0));

  switch (complianceType.penaltyType) {
    case "daily":
      if (penaltyConfig.daily?.perDay) {
        const perDay = penaltyConfig.daily.perDay;
        const amount = perDay * effectiveDaysLate * officers;
        breakdown.push({
          type: "daily",
          rate: perDay,
          days: effectiveDaysLate,
          officers,
          subtotal: amount,
        });
        total += amount;
      }
      if (penaltyConfig.daily?.min !== undefined && penaltyConfig.daily?.max !== undefined) {
        const perDay = Math.min(penaltyConfig.daily.max, Math.max(penaltyConfig.daily.min, 10000));
        const amount = perDay * effectiveDaysLate * officers;
        breakdown.push({
          type: "daily_psc",
          rateMin: penaltyConfig.daily.min,
          rateMax: penaltyConfig.daily.max,
          rateApplied: perDay,
          days: effectiveDaysLate,
          officers,
          subtotal: amount,
        });
        total += amount;
      }
      break;

    case "fixed":
      if (penaltyConfig.fixed?.amount) {
        total += penaltyConfig.fixed.amount * officers;
        breakdown.push({
          type: "fixed",
          rate: penaltyConfig.fixed.amount,
          officers,
          subtotal: total,
        });
      } else if (penaltyConfig.fixed?.[entityType]) {
        const amount = penaltyConfig.fixed[entityType] * officers;
        total += amount;
        breakdown.push({
          type: "fixed_by_entity",
          entityType,
          rate: penaltyConfig.fixed[entityType],
          officers,
          subtotal: amount,
        });
      }
      break;

    case "annual":
      if (penaltyConfig.annual?.[entityType]) {
        total += penaltyConfig.annual[entityType];
        breakdown.push({
          type: "annual",
          entityType,
          rate: penaltyConfig.annual[entityType],
          subtotal: total,
        });
      }
      if (penaltyConfig.daily?.[entityType]) {
        const perDay = penaltyConfig.daily[entityType];
        const dailyAmount = perDay * effectiveDaysLate * officers;
        total += dailyAmount;
        breakdown.push({
          type: "daily",
          entityType,
          rate: perDay,
          days: effectiveDaysLate,
          officers,
          subtotal: dailyAmount,
        });
      }
      break;

    case "per_person":
      if (penaltyConfig.perPerson?.amount) {
        total += penaltyConfig.perPerson.amount * officers;
        breakdown.push({
          type: "per_person",
          rate: penaltyConfig.perPerson.amount,
          persons: officers,
          subtotal: total,
        });
      }
      break;

    default:
      break;
  }

  return { total: Math.round(total * 100) / 100, breakdown, complianceType };
}

function getAnnualReturnDeadlines(entityType, incorporationDate) {
  const incorpDate = new Date(incorporationDate);
  const currentYear = new Date().getFullYear();

  if (entityType === "business-name") {
    const renewalMonth = 4;
    const renewalDay = 30;
    const thisYearDeadline = new Date(currentYear, renewalMonth, renewalDay);
    const nextDeadline = new Date() > thisYearDeadline
      ? new Date(currentYear + 1, renewalMonth, renewalDay)
      : thisYearDeadline;

    return {
      type: "annual_renewal",
      nextDueDate: nextDeadline,
      frequency: "Yearly",
      deadlineMonth: renewalMonth,
      deadlineDay: renewalDay,
    };
  }

  const firstAgmDeadline = new Date(incorpDate);
  firstAgmDeadline.setMonth(firstAgmDeadline.getMonth() + 18);

  const firstReturnDeadline = new Date(firstAgmDeadline);
  firstReturnDeadline.setDate(firstReturnDeadline.getDate() + 42);

  return {
    type: "agm_based",
    firstAgmDeadline,
    firstReturnDeadline,
    subsequentAgmIntervalMonths: 15,
    returnFilingDaysAfterAgm: 42,
    exemption: entityType === "business-name" || entityType === "incorporated-trustee",
  };
}

function getNextComplianceDue(complianceTypeCode, entityType, triggerDate = new Date(), previousDue = null) {
  const complianceType = COMPLIANCE_TYPES[complianceTypeCode];
  if (!complianceType) return null;

  const baseDate = previousDue || triggerDate;
  const deadlineDays = complianceType.filingDeadlineDays || 0;
  const nextDue = new Date(baseDate);
  nextDue.setDate(nextDue.getDate() + deadlineDays);

  if (complianceTypeCode === "BUSINESS_NAME_RENEWAL") {
    nextDue.setDate(nextDue.getDate() + (complianceType.renewalPeriodDays || 1095));
  }

  return nextDue;
}

module.exports = {
  COMPLIANCE_TYPES,
  COMPLIANCE_CATEGORIES,
  PENALTY_RATES,
  PORTAL_STATUS,
  BAD_PORTAL_STATUSES,
  GOOD_PORTAL_STATUSES,
  getComplianceType,
  getComplianceCategory,
  calculatePenalty,
  getAnnualReturnDeadlines,
  getNextComplianceDue,
};
