"use strict";

/**
 * generateCauseListPdf.js
 * Premium Cause List PDF generator.
 *
 * FIXES:
 *  - Wrong page number: uses getCurrentPageNumber() helper
 *  - filename extraction: uses path.basename() — works on Windows and Unix
 *  - Hoisting: addHeader declared before addPageBreak
 *  - outputPath now written to disk via finalizePdf()
 *
 * DESIGN UPGRADES:
 *  - Navy + gold premium palette aligned with firm brand system
 *  - Structured page header with firm name, cause list title, and period
 *  - Gold rule under report period info
 *  - Summary stat bar (total hearings, date range, generated by)
 *  - Table header: navy band with white bold labels
 *  - Alternating row tints
 *  - Lawyer names truncated cleanly with ellipsis
 *  - Footer with separator rule and page count
 *  - Urgent/overdue hearing rows highlighted with danger tint
 */

const PDFDocument = require("pdfkit");
const {
  COLORS,
  FONTS,
  SIZES,
  formatDate,
  formatDateTime,
  getCurrentPageNumber,
  finalizePdf,
} = require("./pdfDesignSystem");

async function generateCauseListPdf(data, res, outputPath) {
  const {
    hearings = [],
    firm,
    periodName,
    startDate,
    endDate,
    totalHearings,
  } = data;

  const chunks = [];
  const doc = new PDFDocument({
    size: "A4",
    layout: "landscape", // More space for 8 columns
    margins: { top: 38, bottom: 38, left: 38, right: 38 },
    bufferPages: true,
    info: {
      Title: `Cause List — ${periodName || "Hearings"}`,
      Author: firm?.name || "Law Firm",
    },
  });

  doc.on("data", (c) => chunks.push(c));

  // Landscape A4: 841.89 × 595.28 pt
  const leftMargin = 38;
  const pageWidth = doc.page.width - 76; // ~766
  const bottomGuard = doc.page.height - 50;
  let y = 0;

  // ── Column layout (landscape) ──────────────────────────────────────────
  // S/N | Date | Day | Case No. | Case Title | Court | Purpose | Lawyer
  const COL = {
    sn: { x: leftMargin + 2, w: 28 },
    date: { x: leftMargin + 32, w: 68 },
    day: { x: leftMargin + 102, w: 52 },
    caseNo: { x: leftMargin + 156, w: 90 },
    title: { x: leftMargin + 248, w: 160 },
    court: { x: leftMargin + 410, w: 108 },
    purpose: { x: leftMargin + 520, w: 115 },
    lawyer: { x: leftMargin + 637, w: 127 },
  };

  // ── Header ── (declared before addPageBreak)
  function addHeader() {
    // Navy band
    doc.rect(0, 0, doc.page.width, 55).fill(COLORS.navy);

    // Firm name
    doc
      .fillColor(COLORS.white)
      .fontSize(SIZES.h1)
      .font(FONTS.bold)
      .text(firm?.name || "Law Firm", leftMargin, 10, { width: 420 });

    // Gold rule
    doc.rect(leftMargin, 32, 50, 1.5).fill(COLORS.gold);

    // "CAUSE LIST" label
    doc
      .fontSize(SIZES.micro)
      .fillColor(COLORS.gold)
      .font(FONTS.bold)
      .text("CAUSE LIST", leftMargin, 36);

    // Period info top-right
    doc
      .fontSize(SIZES.micro)
      .fillColor(COLORS.navyLight)
      .font(FONTS.regular)
      .text(periodName || "Upcoming Hearings", 420, 13, {
        width: 380,
        align: "right",
      });
    doc
      .fontSize(SIZES.micro)
      .fillColor(COLORS.navyLight)
      .font(FONTS.regular)
      .text(`${startDate || ""} – ${endDate || ""}`, 420, 25, {
        width: 380,
        align: "right",
      });
    doc
      .fontSize(SIZES.micro)
      .fillColor(COLORS.textMuted)
      .font(FONTS.regular)
      .text(`Generated: ${formatDateTime(new Date())}`, 420, 37, {
        width: 380,
        align: "right",
      });

    y = 64;
  }

  function addPageBreak() {
    addFooter();
    doc.addPage();
    addHeader();
    drawTableHeader();
  }

  function addFooter() {
    const pageNum = getCurrentPageNumber(doc);
    const footerY = doc.page.height - 25;

    doc
      .moveTo(leftMargin, footerY - 8)
      .lineTo(leftMargin + pageWidth, footerY - 8)
      .lineWidth(0.4)
      .strokeColor(COLORS.gray200)
      .stroke();

    doc
      .fontSize(SIZES.micro)
      .fillColor(COLORS.textMuted)
      .font(FONTS.regular)
      .text(
        `${firm?.name || "Law Firm"}  ·  Cause List: ${periodName || ""}  ·  Page ${pageNum}`,
        leftMargin,
        footerY,
        { align: "center", width: pageWidth },
      );
  }

  function checkY(needed = 22) {
    if (y + needed > bottomGuard) addPageBreak();
  }

  // ── Summary Band ──
  function drawSummaryBand() {
    doc.rect(leftMargin, y, pageWidth, 32).fill(COLORS.navyUltraLight);
    doc
      .rect(leftMargin, y, pageWidth, 32)
      .lineWidth(0.4)
      .strokeColor(COLORS.navyLight)
      .stroke();

    const segW = pageWidth / 3;
    const items = [
      ["Total Hearings", String(totalHearings ?? hearings.length)],
      ["Period", `${startDate || "—"} to ${endDate || "—"}`],
      ["Prepared by", firm?.name || "Law Firm"],
    ];

    items.forEach(([label, val], i) => {
      const sx = leftMargin + 12 + i * segW;
      doc
        .fontSize(SIZES.micro)
        .font(FONTS.regular)
        .fillColor(COLORS.textMuted)
        .text(label, sx, y + 7);
      doc
        .fontSize(SIZES.small)
        .font(FONTS.bold)
        .fillColor(COLORS.navy)
        .text(val, sx, y + 18);
    });

    y += 40;
  }

  // ── Table Header Row ──
  function drawTableHeader() {
    checkY(24);
    doc.rect(leftMargin, y, pageWidth, 22).fill(COLORS.navy);
    doc.fillColor(COLORS.white).fontSize(SIZES.micro).font(FONTS.bold);

    Object.entries(COL).forEach(([key, col]) => {
      const labels = {
        sn: "S/N",
        date: "Hearing Date",
        day: "Day",
        caseNo: "Case / Suit No.",
        title: "Case Title",
        court: "Court",
        purpose: "Purpose",
        lawyer: "Assigned Lawyer(s)",
      };
      doc.text(labels[key], col.x, y + 7, { width: col.w });
    });

    y += 26;
  }

  // ── Render ──
  addHeader();
  drawSummaryBand();

  // Gold rule before table
  doc.rect(leftMargin, y, pageWidth, 1.5).fill(COLORS.gold);
  y += 8;

  drawTableHeader();

  hearings.forEach((hearing, idx) => {
    checkY(22);

    // Check if hearing is today or past (highlight overdue in red tint)
    const hearingDate = hearing.hearingDate
      ? new Date(hearing.hearingDate)
      : null;
    const isToday =
      hearingDate && hearingDate.toDateString() === new Date().toDateString();
    const isPast = hearingDate && hearingDate < new Date() && !isToday;

    let rowBg;
    if (isToday) rowBg = COLORS.goldLight;
    else if (isPast) rowBg = COLORS.dangerLight;
    else if (idx % 2 === 1) rowBg = COLORS.gray50;
    else rowBg = COLORS.white;

    doc.rect(leftMargin, y - 2, pageWidth, 20).fill(rowBg);

    // Left color indicator stripe
    const stripeColor = isToday
      ? COLORS.gold
      : isPast
        ? COLORS.danger
        : COLORS.navy;
    doc.rect(leftMargin, y - 2, 3, 20).fill(stripeColor);

    const textColor = isPast ? COLORS.danger : COLORS.textPrimary;
    const dayStr = hearingDate
      ? hearingDate.toLocaleDateString("en-GB", { weekday: "long" })
      : "N/A";

    const lawyerStr = Array.isArray(hearing.lawyerPresent)
      ? hearing.lawyerPresent
          .map((l) =>
            `${(l.firstName || "")[0] || ""}. ${l.lastName || ""}`.trim(),
          )
          .join(", ")
      : hearing.lawyerPresent || "N/A";

    doc.fillColor(textColor).fontSize(SIZES.micro).font(FONTS.regular);

    doc.text(String(idx + 1), COL.sn.x, y + 2, { width: COL.sn.w });

    doc
      .font(isPast || isToday ? FONTS.bold : FONTS.regular)
      .text(formatDate(hearing.hearingDate), COL.date.x, y + 2, {
        width: COL.date.w,
      });

    doc
      .font(FONTS.regular)
      .text(dayStr, COL.day.x, y + 2, { width: COL.day.w });

    doc
      .font(FONTS.bold)
      .fillColor(COLORS.navy)
      .text(
        hearing.suitNo || hearing.matterNumber || "N/A",
        COL.caseNo.x,
        y + 2,
        { width: COL.caseNo.w },
      );

    doc
      .font(FONTS.regular)
      .fillColor(textColor)
      .text(truncate(hearing.title || "N/A", 32), COL.title.x, y + 2, {
        width: COL.title.w,
      });

    doc.text(truncate(hearing.courtName || "N/A", 20), COL.court.x, y + 2, {
      width: COL.court.w,
    });

    doc.text(truncate(hearing.purpose || "N/A", 22), COL.purpose.x, y + 2, {
      width: COL.purpose.w,
    });

    doc
      .fillColor(COLORS.navy)
      .font(FONTS.bold)
      .text(truncate(lawyerStr, 24), COL.lawyer.x, y + 2, {
        width: COL.lawyer.w,
      });

    y += 20;
  });

  // ── Legend ──
  y += 14;
  checkY(30);
  doc.rect(leftMargin, y, pageWidth, 24).fill(COLORS.gray50);

  const legendItems = [
    { color: COLORS.gold, label: "Today's hearings" },
    { color: COLORS.danger, label: "Past / overdue hearings" },
    { color: COLORS.navy, label: "Upcoming hearings" },
  ];
  let lx = leftMargin + 12;
  legendItems.forEach(({ color, label }) => {
    doc.rect(lx, y + 8, 8, 8).fill(color);
    doc
      .fontSize(SIZES.micro)
      .font(FONTS.regular)
      .fillColor(COLORS.textSecondary)
      .text(label, lx + 12, y + 9);
    lx += 160;
  });

  addFooter();

  return finalizePdf(doc, chunks, res, outputPath);
}

function truncate(str, maxLen) {
  if (!str) return "—";
  return str.length > maxLen ? `${str.substring(0, maxLen - 1)}…` : str;
}

module.exports = { generateCauseListPdf };
