const mongoose = require("mongoose");

const exportSchema = new mongoose.Schema(
  {
    format: {
      type: String,
      enum: ["pdf", "docx", "txt"],
      required: true,
    },
    exportedAt: {
      type: Date,
      default: Date.now,
    },
    exportedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
    },
  },
  { _id: false },
);

const generatedDocumentSchema = new mongoose.Schema(
  {
    firmId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Firm",
      required: [true, "Firm ID is required"],
      index: true,
    },
    templateId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Template",
      required: [true, "Template ID is required"],
    },
    matterId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Matter",
    },
    clientId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
    },
    title: {
      type: String,
      required: [true, "Document title is required"],
      trim: true,
    },
    content: {
      type: String,
      required: [true, "Document content is required"],
    },
    filledData: {
      type: Map,
      of: String,
    },
    exports: [exportSchema],
    status: {
      type: String,
      enum: ["draft", "final", "signed", "archived"],
      default: "draft",
    },
    generatedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: [true, "Generated by user is required"],
    },
    isDeleted: {
      type: Boolean,
      default: false,
      select: false,
    },
  },
  {
    timestamps: true,
  }
);

generatedDocumentSchema.index({ firmId: 1, templateId: 1 });
generatedDocumentSchema.index({ firmId: 1, matterId: 1 });
generatedDocumentSchema.index({ firmId: 1, generatedBy: 1 });

const GeneratedDocument = mongoose.model(
  "GeneratedDocument",
  generatedDocumentSchema
);

module.exports = GeneratedDocument;
